import { Download, Share2 } from "lucide-react";
import { Button } from "@/components/ui/button";
import { useToast } from "@/hooks/use-toast";
import { motion } from "framer-motion";

interface ExportResultsProps {
  prediction: {
    disease?: string;
    treatment?: string;
  };
  symptoms: string;
}

export function ExportResults({ prediction, symptoms }: ExportResultsProps) {
  const { toast } = useToast();

  const generateReport = () => {
    const report = `
╔════════════════════════════════════════════════════════════╗
║           HEALTH & WELLNESS ANALYSIS REPORT                ║
╚════════════════════════════════════════════════════════════╝

📅 Date: ${new Date().toLocaleDateString()}
⏰ Time: ${new Date().toLocaleTimeString()}

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

📝 SYMPTOMS DESCRIBED:
${symptoms}

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

🔍 ANALYSIS RESULT:
${prediction.disease}

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

💊 RECOMMENDED APPROACH:
${prediction.treatment}

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

⚠️ DISCLAIMER:
This is an AI-powered analysis for educational purposes only.
Please consult a healthcare professional for proper diagnosis.

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
Generated by Health & Wellness Analyzer
`;
    return report;
  };

  const handleDownload = () => {
    const report = generateReport();
    const blob = new Blob([report], { type: "text/plain" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `health-analysis-${Date.now()}.txt`;
    a.click();
    URL.revokeObjectURL(url);
    
    toast({
      title: "Report Downloaded",
      description: "Your analysis report has been saved.",
    });
  };

  const handleShare = async () => {
    const report = generateReport();
    
    if (navigator.share) {
      try {
        await navigator.share({
          title: "Health & Wellness Analysis",
          text: report,
        });
      } catch (err) {
        // User cancelled share
      }
    } else {
      await navigator.clipboard.writeText(report);
      toast({
        title: "Copied to Clipboard",
        description: "Report copied! You can now paste it anywhere.",
      });
    }
  };

  return (
    <motion.div 
      initial={{ opacity: 0, y: 10 }}
      animate={{ opacity: 1, y: 0 }}
      className="flex gap-2 mt-4"
    >
      <Button
        onClick={handleDownload}
        variant="outline"
        size="sm"
        className="flex-1 bg-white/50 dark:bg-gray-800/50"
      >
        <Download className="h-4 w-4 mr-2" />
        Download Report
      </Button>
      <Button
        onClick={handleShare}
        variant="outline"
        size="sm"
        className="flex-1 bg-white/50 dark:bg-gray-800/50"
      >
        <Share2 className="h-4 w-4 mr-2" />
        Share
      </Button>
    </motion.div>
  );
}
